<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Overview" data-toc-modified-id="Overview-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Overview</a></span></li><li><span><a href="#Notebook-Configuration" data-toc-modified-id="Notebook-Configuration-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Notebook Configuration</a></span><ul class="toc-item"><li><span><a href="#Google-drive" data-toc-modified-id="Google-drive-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Google drive</a></span></li><li><span><a href="#Warning" data-toc-modified-id="Warning-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Warning</a></span></li><li><span><a href="#Matplotlib" data-toc-modified-id="Matplotlib-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Matplotlib</a></span></li><li><span><a href="#TensorFlow" data-toc-modified-id="TensorFlow-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>TensorFlow</a></span></li><li><span><a href="#Random-seed" data-toc-modified-id="Random-seed-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Random seed</a></span></li></ul></li><li><span><a href="#Data-Preprocessing" data-toc-modified-id="Data-Preprocessing-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Preprocessing</a></span><ul class="toc-item"><li><span><a href="#Loading-the-data" data-toc-modified-id="Loading-the-data-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Loading the data</a></span></li><li><span><a href="#Splitting-the-data" data-toc-modified-id="Splitting-the-data-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Splitting the data</a></span></li><li><span><a href="#Handling-uncommon-features" data-toc-modified-id="Handling-uncommon-features-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Handling uncommon features</a></span><ul class="toc-item"><li><span><a href="#Identifying-uncommon-features" data-toc-modified-id="Identifying-uncommon-features-3.3.1"><span class="toc-item-num">3.3.1&nbsp;&nbsp;</span>Identifying uncommon features</a></span></li><li><span><a href="#Removing-uncommon-features" data-toc-modified-id="Removing-uncommon-features-3.3.2"><span class="toc-item-num">3.3.2&nbsp;&nbsp;</span>Removing uncommon features</a></span></li></ul></li><li><span><a href="#Handling-identifiers" data-toc-modified-id="Handling-identifiers-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Handling identifiers</a></span><ul class="toc-item"><li><span><a href="#Combining-the-training,-validation-and-test-data" data-toc-modified-id="Combining-the-training,-validation-and-test-data-3.4.1"><span class="toc-item-num">3.4.1&nbsp;&nbsp;</span>Combining the training, validation and test data</a></span></li><li><span><a href="#Identifying-identifiers" data-toc-modified-id="Identifying-identifiers-3.4.2"><span class="toc-item-num">3.4.2&nbsp;&nbsp;</span>Identifying identifiers</a></span></li><li><span><a href="#Removing-identifiers" data-toc-modified-id="Removing-identifiers-3.4.3"><span class="toc-item-num">3.4.3&nbsp;&nbsp;</span>Removing identifiers</a></span></li></ul></li><li><span><a href="#Handling-date-time-variables" data-toc-modified-id="Handling-date-time-variables-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Handling date time variables</a></span><ul class="toc-item"><li><span><a href="#Transforming-date-time-variables" data-toc-modified-id="Transforming-date-time-variables-3.5.1"><span class="toc-item-num">3.5.1&nbsp;&nbsp;</span>Transforming date time variables</a></span></li></ul></li><li><span><a href="#Handling-missing-data" data-toc-modified-id="Handling-missing-data-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Handling missing data</a></span><ul class="toc-item"><li><span><a href="#Combining-the-training,-validation-and-test-data" data-toc-modified-id="Combining-the-training,-validation-and-test-data-3.6.1"><span class="toc-item-num">3.6.1&nbsp;&nbsp;</span>Combining the training, validation and test data</a></span></li><li><span><a href="#Identifying-missing-values" data-toc-modified-id="Identifying-missing-values-3.6.2"><span class="toc-item-num">3.6.2&nbsp;&nbsp;</span>Identifying missing values</a></span></li><li><span><a href="#Separating-the-training,-validation-and-test-data" data-toc-modified-id="Separating-the-training,-validation-and-test-data-3.6.3"><span class="toc-item-num">3.6.3&nbsp;&nbsp;</span>Separating the training, validation and test data</a></span></li><li><span><a href="#Removing-missing-values" data-toc-modified-id="Removing-missing-values-3.6.4"><span class="toc-item-num">3.6.4&nbsp;&nbsp;</span>Removing missing values</a></span></li><li><span><a href="#Imputing-missing-values" data-toc-modified-id="Imputing-missing-values-3.6.5"><span class="toc-item-num">3.6.5&nbsp;&nbsp;</span>Imputing missing values</a></span></li></ul></li><li><span><a href="#Encoding-the-data" data-toc-modified-id="Encoding-the-data-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Encoding the data</a></span><ul class="toc-item"><li><span><a href="#Combining-the-training,-validation-and-test-data" data-toc-modified-id="Combining-the-training,-validation-and-test-data-3.7.1"><span class="toc-item-num">3.7.1&nbsp;&nbsp;</span>Combining the training, validation and test data</a></span></li><li><span><a href="#Identifying-categorical-variables" data-toc-modified-id="Identifying-categorical-variables-3.7.2"><span class="toc-item-num">3.7.2&nbsp;&nbsp;</span>Identifying categorical variables</a></span></li><li><span><a href="#Encoding-categorical-features" data-toc-modified-id="Encoding-categorical-features-3.7.3"><span class="toc-item-num">3.7.3&nbsp;&nbsp;</span>Encoding categorical features</a></span></li><li><span><a href="#Separating-the-training,-validation-and-test-data" data-toc-modified-id="Separating-the-training,-validation-and-test-data-3.7.4"><span class="toc-item-num">3.7.4&nbsp;&nbsp;</span>Separating the training, validation and test data</a></span></li></ul></li><li><span><a href="#Splitting-the-feature-and-target" data-toc-modified-id="Splitting-the-feature-and-target-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>Splitting the feature and target</a></span></li><li><span><a href="#Scaling-the-data" data-toc-modified-id="Scaling-the-data-3.9"><span class="toc-item-num">3.9&nbsp;&nbsp;</span>Scaling the data</a></span><ul class="toc-item"><li><span><a href="#Min-Max-Normalization" data-toc-modified-id="Min-Max-Normalization-3.9.1"><span class="toc-item-num">3.9.1&nbsp;&nbsp;</span>Min-Max Normalization</a></span><ul class="toc-item"><li><span><a href="#Normalizing-the-features" data-toc-modified-id="Normalizing-the-features-3.9.1.1"><span class="toc-item-num">3.9.1.1&nbsp;&nbsp;</span>Normalizing the features</a></span></li><li><span><a href="#Normalizing-the-target" data-toc-modified-id="Normalizing-the-target-3.9.1.2"><span class="toc-item-num">3.9.1.2&nbsp;&nbsp;</span>Normalizing the target</a></span></li></ul></li><li><span><a href="#Standardization" data-toc-modified-id="Standardization-3.9.2"><span class="toc-item-num">3.9.2&nbsp;&nbsp;</span>Standardization</a></span><ul class="toc-item"><li><span><a href="#Standardizing-the-features" data-toc-modified-id="Standardizing-the-features-3.9.2.1"><span class="toc-item-num">3.9.2.1&nbsp;&nbsp;</span>Standardizing the features</a></span></li><li><span><a href="#Standardizing-the-target" data-toc-modified-id="Standardizing-the-target-3.9.2.2"><span class="toc-item-num">3.9.2.2&nbsp;&nbsp;</span>Standardizing the target</a></span></li></ul></li></ul></li></ul></li></ul></div>

<b>
<p>
<center>
<font size="5">
Popular Machine Learning Methods: Idea, Practice and Math
</font>
</center>
</p>

<p>
<center>
<font size="4">
Part 2, Chapter 1: Data Preprocessing
</font>
</center>
</p>
    
<p>
<center>
<font size="4">
Code Example: Regression
</font>
</center>
</p>

<p>
<center>
<font size="3">
Data Science, Columbian College of Arts & Sciences, George Washington University
</font>
</center>
</p>

<p>
<center>
<font size="3">
Yuxiao Huang
</font>
</center>
</p>
</b>

# Overview

- This notebook includes the code example for Data Preprocessing (Part 2, Chapter 1).
- See the accompanied slides in our [github repository](https://github.com/yuxiaohuang/teaching/tree/master/gwu/machine_learning_I/fall_2020/slides/p2_shallow_learning/p2_c2_supervised_learning/p2_c1_data_preprocessing).

# Notebook Configuration

## Google drive

In [1]:
from google.colab import drive
import sys

# Mount Google Drive
drive.mount('/content/drive')

# Get the absolute path of the current folder
abspath_curr = '/content/drive/My Drive/Colab Notebooks/education/youtube/machine_learning/code/data_preprocessing/'

# Get the absolute path of the data folder
abspath_data = '/content/drive/My Drive/Colab Notebooks/education/youtube/machine_learning/data/data_preprocessing/'

# Get the absolute path of the result folder
abspath_result = '/content/drive/My Drive/Colab Notebooks/education/youtube/machine_learning/result/data_preprocessing/'

# Get the absolute path of the helper folder
abspath_helper = '/content/drive/My Drive/Colab Notebooks/education/youtube/machine_learning/code/helper/'

Mounted at /content/drive

## Warning

In [2]:
import warnings

# Ignore warnings
warnings.filterwarnings('ignore')

## Matplotlib

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline 

# Set matplotlib sizes
plt.rc('font', size=20)
plt.rc('axes', titlesize=20)
plt.rc('axes', labelsize=20)
plt.rc('xtick', labelsize=20)
plt.rc('ytick', labelsize=20)
plt.rc('legend', fontsize=20)
plt.rc('figure', titlesize=20)

## TensorFlow

In [4]:
# The magic below allows us to use tensorflow version 2.x
%tensorflow_version 2.x 
import tensorflow as tf
from tensorflow import keras

## Random seed

In [5]:
# The random seed
random_seed = 42

# Set random seed in tensorflow
tf.random.set_seed(random_seed)

# Set random seed in numpy
import numpy as np
np.random.seed(random_seed)

# Data Preprocessing

In [6]:
# Change working directory to the absolute path of the helper folder
%cd $abspath_helper

# Import the helper
%run helper.ipynb

/content/drive/My Drive/Colab Notebooks/education/youtube/machine_learning/code/helper

## Loading the data

In this code example, we will use the [House Prices (Advanced Regression Techniques) dataset](https://www.kaggle.com/c/house-prices-advanced-regression-techniques).

In [7]:
import pandas as pd

# Load the raw training data
df_raw_train = pd.read_csv(f'{abspath_data}/house_prices_advanced_regression_techniques/train.csv',
                           header=0)
# Make a copy of df_raw_train
df_train = df_raw_train.copy(deep=True)

# Load the raw test data
df_raw_test = pd.read_csv(f'{abspath_data}/house_prices_advanced_regression_techniques/test.csv',
                          header=0)
# Make a copy of df_raw_test
df_test = df_raw_test.copy(deep=True)

# Get the name of the target
target = 'SalePrice'

In [8]:
# Print the dimension of df_train
pd.DataFrame([[df_train.shape[0], df_train.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0    1460         81

In [9]:
# Print the dimension of df_test
pd.DataFrame([[df_test.shape[0], df_test.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0    1459         80

In [10]:
# Print the first 5 rows of df_train
df_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [11]:
# Print the first 5 rows of df_test
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

## Splitting the data
The code below shows how to divide the training data into training (80%) and validation (20%).

In [12]:
from sklearn.model_selection import train_test_split

# Divide the training data into training (80%) and validation (20%)
df_train, df_val = train_test_split(df_train, train_size=0.8, random_state=random_seed)

# Reset the index
df_train, df_val = df_train.reset_index(drop=True), df_val.reset_index(drop=True)

In [13]:
# Print the dimension of df_train
pd.DataFrame([[df_train.shape[0], df_train.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0    1168         81

In [14]:
# Print the dimension of df_val
pd.DataFrame([[df_val.shape[0], df_val.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0     292         81

## Handling uncommon features

### Identifying uncommon features

The code below shows how to find common variables between the training, validation and test data.

In [15]:
# Call common_var_checker
# See the implementation in pmlm_utilities.ipynb
df_common_var = common_var_checker(df_train, df_val, df_test, target)

# Print df_common_var
df_common_var

      common var
0       1stFlrSF
1       2ndFlrSF
2      3SsnPorch
3          Alley
4   BedroomAbvGr
..           ...
76     Utilities
77    WoodDeckSF
78     YearBuilt
79  YearRemodAdd
80        YrSold

[81 rows x 1 columns]

The code below shows how to find features in the training data but not in the validation or test data.

In [16]:
# Get the features in the training data but not in the validation or test data
uncommon_feature_train_not_val_test = np.setdiff1d(df_train.columns, df_common_var['common var'])

# Print the uncommon features
pd.DataFrame(uncommon_feature_train_not_val_test, columns=['uncommon feature'])

Empty DataFrame
Columns: [uncommon feature]
Index: []

The code below shows how to find the features in the validation data but not in the training or test data.

In [17]:
# Get the features in the validation data but not in the training or test data
uncommon_feature_val_not_train_test = np.setdiff1d(df_val.columns, df_common_var['common var'])

# Print the uncommon features
pd.DataFrame(uncommon_feature_val_not_train_test, columns=['uncommon feature'])

Empty DataFrame
Columns: [uncommon feature]
Index: []

The code below shows how to find the features in the test data but not in the training or validation data.

In [18]:
# Get the features in the test data but not in the training or validation data
uncommon_feature_test_not_train_val = np.setdiff1d(df_test.columns, df_common_var['common var'])

# Print the uncommon features
pd.DataFrame(uncommon_feature_test_not_train_val, columns=['uncommon feature'])

Empty DataFrame
Columns: [uncommon feature]
Index: []

### Removing uncommon features

In [19]:
# Remove the uncommon features from the training data
df_train = df_train.drop(columns=uncommon_feature_train_not_val_test)

# Print the first 5 rows of df_train
df_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,255,20,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,145000
1,1067,60,RL,59.0,7837,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,178000
2,639,30,RL,67.0,8777,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2008,WD,Normal,85000
3,800,50,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2007,WD,Normal,175000
4,381,50,RL,50.0,5000,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,127000

In [20]:
# Remove the uncommon features from the validation data
df_val = df_val.drop(columns=uncommon_feature_val_not_train_test)

# Print the first 5 rows of df_val
df_val.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,893,20,RL,70.0,8414,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2006,WD,Normal,154500
1,1106,60,RL,98.0,12256,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,325000
2,414,30,RM,56.0,8960,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,115000
3,523,50,RM,50.0,5000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2006,WD,Normal,159000
4,1037,20,RL,89.0,12898,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,315500

In [21]:
# Remove the uncommon features from the test data
df_test = df_test.drop(columns=uncommon_feature_test_not_train_val)

# Print the first 5 rows of df_test
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

## Handling identifiers

### Combining the training, validation and test data
The code below shows how to combine the training, validation and test data.

In [22]:
# Combine df_train, df_val and df_test
df = pd.concat([df_train, df_val, df_test], sort=False)

### Identifying identifiers
The code below shows how to find identifiers from data.

In [23]:
# Call id_checker on df
# See the implementation in pmlm_utilities.ipynb
df_id = id_checker(df)

# Print the first 5 rows of df_id
df_id.head()

     Id
0   255
1  1067
2   639
3   800
4   381

### Removing identifiers
The code below shows how to remove identifiers from data.

In [24]:
import numpy as np

# Remove identifiers from df_train
df_train.drop(columns=np.intersect1d(df_id.columns, df_train.columns), inplace=True)

# Remove identifiers from df_val
df_val.drop(columns=np.intersect1d(df_id.columns, df_val.columns), inplace=True)

# Remove identifiers from df_test
df_test.drop(columns=np.intersect1d(df_id.columns, df_test.columns), inplace=True)

In [25]:
# Print the first 5 rows of df_train
df_train.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,20,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,145000
1,60,RL,59.0,7837,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,178000
2,30,RL,67.0,8777,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,5,2008,WD,Normal,85000
3,50,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,MnPrv,NaN,0,6,2007,WD,Normal,175000
4,50,RL,50.0,5000,Pave,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,127000

In [26]:
# Print the first 5 rows of df_val
df_val.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,20,RL,70.0,8414,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2006,WD,Normal,154500
1,60,RL,98.0,12256,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,325000
2,30,RM,56.0,8960,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,115000
3,50,RM,50.0,5000,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,10,2006,WD,Normal,159000
4,20,RL,89.0,12898,Pave,NaN,IR1,HLS,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,315500

In [27]:
# Print the first 5 rows of df_test
df_test.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

## Handling date time variables

### Transforming date time variables
The code below shows how to transform date time variables into the following 6 datetime types:
- year
- month
- day
- hour
- minute
- second

In [28]:
# Get the date time variables
datetime_vars = []

In [29]:
# Call datetime_transformer on df_train
# See the implementation in pmlm_utilities.ipynb
df_train = datetime_transformer(df_train, datetime_vars)

# Print the first 5 rows of df_train
df_train.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,20,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,145000
1,60,RL,59.0,7837,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,178000
2,30,RL,67.0,8777,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,5,2008,WD,Normal,85000
3,50,RL,60.0,7200,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,MnPrv,NaN,0,6,2007,WD,Normal,175000
4,50,RL,50.0,5000,Pave,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,127000

In [30]:
# Call datetime_transformer on df_val
# See the implementation in pmlm_utilities.ipynb
df_val = datetime_transformer(df_val, datetime_vars)

# Print the first 5 rows of df_val
df_val.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,20,RL,70.0,8414,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2006,WD,Normal,154500
1,60,RL,98.0,12256,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,325000
2,30,RM,56.0,8960,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,115000
3,50,RM,50.0,5000,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,10,2006,WD,Normal,159000
4,20,RL,89.0,12898,Pave,NaN,IR1,HLS,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2009,WD,Normal,315500

In [31]:
# Call datetime_transformer on df_test
# See the implementation in pmlm_utilities.ipynb
df_test = datetime_transformer(df_test, datetime_vars)

# Print the first 5 rows of df_test
df_test.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

## Handling missing data

### Combining the training, validation and test data
The code below shows how to combine the training, validation and test data.

In [32]:
# Combine df_train, df_val and df_test
df = pd.concat([df_train, df_val, df_test], sort=False)

### Identifying missing values

The code below shows how to find variables with NaN, their proportion of NaN and data type.

In [33]:
# Call nan_checker on df
# See the implementation in pmlm_utilities.ipynb
df_nan = nan_checker(df)

# Print df_nan
df_nan

             var  proportion    dtype
0         PoolQC    0.996574   object
1    MiscFeature    0.964029   object
2          Alley    0.932169   object
3          Fence    0.804385   object
4      SalePrice    0.499829  float64
5    FireplaceQu    0.486468   object
6    LotFrontage    0.166495  float64
7     GarageCond    0.054471   object
8    GarageYrBlt    0.054471  float64
9   GarageFinish    0.054471   object
10    GarageQual    0.054471   object
11    GarageType    0.053786   object
12  BsmtExposure    0.028092   object
13      BsmtCond    0.028092   object
14      BsmtQual    0.027749   object
15  BsmtFinType2    0.027407   object
16  BsmtFinType1    0.027064   object
17    MasVnrType    0.008222   object
18    MasVnrArea    0.007879  float64
19      MSZoning    0.001370   object
20    Functional    0.000685   object
21  BsmtHalfBath    0.000685  float64
22  BsmtFullBath    0.000685  float64
23     Utilities    0.000685   object
24   KitchenQual    0.000343   object
25   TotalBsmtSF    0.000343  float64
26     BsmtUnfSF    0.000343  float64
27    GarageCars    0.000343  float64
28    GarageArea    0.000343  float64
29    BsmtFinSF2    0.000343  float64
30    BsmtFinSF1    0.000343  float64
31   Exterior2nd    0.000343   object
32   Exterior1st    0.000343   object
33      SaleType    0.000343   object
34    Electrical    0.000343   object

In [34]:
# Print the unique data type of variables with NaN
pd.DataFrame(df_nan['dtype'].unique(), columns=['dtype'])

     dtype
0   object
1  float64

The code below shows how to use data type to select variables with missing values in the combined data.

In [35]:
# Get the variables with missing values, their proportion of missing values and data type
df_miss = df_nan[df_nan['dtype'] == 'float64'].reset_index(drop=True)

# Print df_miss
df_miss

             var  proportion    dtype
0      SalePrice    0.499829  float64
1    LotFrontage    0.166495  float64
2    GarageYrBlt    0.054471  float64
3     MasVnrArea    0.007879  float64
4   BsmtHalfBath    0.000685  float64
5   BsmtFullBath    0.000685  float64
6    TotalBsmtSF    0.000343  float64
7      BsmtUnfSF    0.000343  float64
8     GarageCars    0.000343  float64
9     GarageArea    0.000343  float64
10    BsmtFinSF2    0.000343  float64
11    BsmtFinSF1    0.000343  float64

### Separating the training, validation and test data
The code below shows how to separate the training, validation and test data.

In [36]:
# Separating the training data
df_train = df.iloc[:df_train.shape[0], :]

# Separating the validation data
df_val = df.iloc[df_train.shape[0]:df_train.shape[0] + df_val.shape[0], :]

# Separating the test data
df_test = df.iloc[df_train.shape[0] + df_val.shape[0]:, :]

In [37]:
# Print the dimension of df_train
pd.DataFrame([[df_train.shape[0], df_train.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0    1168         80

In [38]:
# Print the dimension of df_val
pd.DataFrame([[df_val.shape[0], df_val.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0     292         80

In [39]:
# Print the dimension of df_test
pd.DataFrame([[df_test.shape[0], df_test.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0    1459         80

### Removing missing values
The code below shows how to remove rows with missing values .

In [40]:
# If there are missing values
if len(df_miss['var']) > 0:
    # Remove rows with missing values from df_train
    df_remove_train = df_train.dropna(subset=np.intersect1d(df_miss['var'], df_train.columns),
                                    inplace=False)

    # Remove rows with missing values from df_val
    df_remove_val = df_val.dropna(subset=np.intersect1d(df_miss['var'], df_val.columns),
                                    inplace=False)

    # Remove rows with missing values from df_test
    df_remove_test = df_test.dropna(subset=np.intersect1d(df_miss['var'], df_test.columns),
                                inplace=False)

### Imputing missing values
The code below shows how to use the mean of a numerical feature to impute its missing values.

In [41]:
from sklearn.impute import SimpleImputer

# If there are missing values
if len(df_miss['var']) > 0:
    # The SimpleImputer
    si = SimpleImputer(missing_values=np.nan, strategy='mean')

    # Impute the variables with missing values in df_train, df_val and df_test 
    df_train[df_miss['var']] = si.fit_transform(df_train[df_miss['var']])
    df_val[df_miss['var']] = si.transform(df_val[df_miss['var']])
    df_test[df_miss['var']] = si.transform(df_test[df_miss['var']])

## Encoding the data

### Combining the training, validation and test data
The code below shows how to combine the training, validation and test data.

In [42]:
# Combine df_train, df_val and df_test
df = pd.concat([df_train, df_val, df_test], sort=False)

# Print the unique data type of variables in df
pd.DataFrame(df.dtypes.unique(), columns=['dtype'])

     dtype
0    int64
1   object
2  float64

### Identifying categorical variables

The code below shows how to find categorical variables (whose data type is dtype) and their number of unique value.

In [43]:
# Call cat_var_checker on df
# See the implementation in pmlm_utilities.ipynb
df_cat = cat_var_checker(df)

# Print the dataframe
df_cat

              var  nunique
0    Neighborhood       25
1     Exterior2nd       17
2     Exterior1st       16
3        SaleType       10
4      Condition1        9
5      Condition2        8
6        RoofMatl        8
7      Functional        8
8      HouseStyle        8
9    BsmtFinType2        7
10   BsmtFinType1        7
11     GarageType        7
12     Electrical        6
13     Foundation        6
14        Heating        6
15    FireplaceQu        6
16     GarageQual        6
17     GarageCond        6
18       MSZoning        6
19  SaleCondition        6
20      RoofStyle        6
21      ExterCond        5
22       BldgType        5
23    MiscFeature        5
24          Fence        5
25      LotConfig        5
26    KitchenQual        5
27       BsmtQual        5
28      HeatingQC        5
29     MasVnrType        5
30   BsmtExposure        5
31       BsmtCond        5
32      ExterQual        4
33   GarageFinish        4
34    LandContour        4
35       LotShape        4
36         PoolQC        4
37      Utilities        3
38     PavedDrive        3
39          Alley        3
40      LandSlope        3
41     CentralAir        2
42         Street        2

### Encoding categorical features
The code below shows how to encode categorical features in the combined data.

In [44]:
# One-hot-encode the categorical features in the combined data
df = pd.get_dummies(df, columns=np.setdiff1d(df_cat['var'], [target]))

# Print the first 5 rows of df
df.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,Street_Grvl,Street_Pave,Utilities_AllPub,Utilities_NoSeWa
0,20,70.0,8400,5,6,1957,1957,0.0,922.0,0.0,...,0,0,0,0,0,1,0,1,1,0
1,60,59.0,7837,6,7,1993,1994,0.0,0.0,0.0,...,0,0,0,0,0,1,0,1,1,0
2,30,67.0,8777,5,7,1910,1950,0.0,0.0,0.0,...,0,0,0,0,0,1,0,1,1,0
3,50,60.0,7200,5,7,1937,1950,252.0,569.0,0.0,...,0,0,0,0,0,1,0,1,1,0
4,50,50.0,5000,5,6,1924,1950,0.0,218.0,0.0,...,0,0,0,0,0,1,0,1,1,0

### Separating the training, validation and test data
The code below shows how to separate the training, validation and test data.

In [45]:
# Separating the training data
df_train = df.iloc[:df_train.shape[0], :]

# Separating the validation data
df_val = df.iloc[df_train.shape[0]:df_train.shape[0] + df_val.shape[0], :]

# Separating the test data
df_test = df.iloc[df_train.shape[0] + df_val.shape[0]:, :]

In [46]:
# Print the dimension of df_train
pd.DataFrame([[df_train.shape[0], df_train.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0    1168        289

In [47]:
# Print the dimension of df_val
pd.DataFrame([[df_val.shape[0], df_val.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0     292        289

In [48]:
# Print the dimension of df_test
pd.DataFrame([[df_test.shape[0], df_test.shape[1]]], columns=['# rows', '# columns'])

   # rows  # columns
0    1459        289

## Splitting the feature and target
The code below shows how to split the feature and target.

In [49]:
# Get the feature matrix
X_train = df_train[np.setdiff1d(df_train.columns, [target])].values
X_val = df_val[np.setdiff1d(df_val.columns, [target])].values
X_test = df_test[np.setdiff1d(df_test.columns, [target])].values

# Get the target vector
y_train = df_train[target].values
y_val = df_val[target].values
y_test = df_test[target].values

## Scaling the data

### Min-Max Normalization
The code below shows how to normalize the data.

In [50]:
from sklearn.preprocessing import MinMaxScaler

# The MinMaxScaler
mms = MinMaxScaler()

#### Normalizing the features
The code below shows how to normalize the features.

In [51]:
# Normalize the training data
X_mms_train = mms.fit_transform(X_train)

# Normalize the validation data
X_mms_val = mms.transform(X_val)

# Normalize the test data
X_mms_test = mms.transform(X_test)

#### Normalizing the target
The code below shows how to normalize the features.

In [52]:
# Normalize the training data
y_mms_train = mms.fit_transform(y_train.reshape(-1, 1)).reshape(-1)

# Normalize the validation data
y_mms_val = mms.transform(y_val.reshape(-1, 1)).reshape(-1)

# Normalize the test data
y_mms_test = mms.transform(y_test.reshape(-1, 1)).reshape(-1)

### Standardization
The code below shows how to standardize the data.

In [53]:
from sklearn.preprocessing import StandardScaler

# The StandardScaler
ss = StandardScaler()

#### Standardizing the features
The code below shows how to standardize the features.

In [54]:
# Standardize the training data
X_train = ss.fit_transform(X_train)

# Standardize the validation data
X_val = ss.transform(X_val)

# Standardize the test data
X_test = ss.transform(X_test)

#### Standardizing the target
The code below shows how to standardize the features.

In [55]:
# Standardize the training data
y_train = ss.fit_transform(y_train.reshape(-1, 1)).reshape(-1)

# Standardize the validation data
y_val = ss.transform(y_val.reshape(-1, 1)).reshape(-1)

# Standardize the test data
y_test = ss.transform(y_test.reshape(-1, 1)).reshape(-1)